crop_thresh: 0.5
attr_thresh: 0.5
kpt_thresh: 0.5
visual: False
warmup_frame: 10



VIDEO_ACTION:
  model_dir: source/model1
  batch_size: 1
  frame_len: 8
  sample_freq: 4
  short_size: 340
  target_size: 320
  enable: True
